runmode: standalone  # standalone：独立运行、zookeeper：主从配置
brokerName: broker-a # 主从模式下名称相同
storeType: rocksdb   # 存储引擎 默认 rocksdb
consumer:
  type: rocketmq
  topic: mytest
  groupName: smartMQGroup
props:
  nameServer: 192.168.1.9:9876 #名字服务地址
  batchSize: 10                #批量消费消息条数